---

- name: "Create directory for {{ directory_type | default('nginx') }} - {{ item }}"
  ansible.builtin.file:
    path: "{{ nginx_service_config_path }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
