---

- name: "Create Nginx SSL Directory - {{ item }}"
  ansible.builtin.file:
    path: "{{ nginx_service_ssl_path }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
