---

- name: Install Nginx package
  ansible.builtin.yum:
    name: "{{ nginx_service_packages }}"
    state: present

- name: Create Nginx configuration directories
  ansible.builtin.file:
    path: "{{ nginx_service_config_path }}/{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - "global"
    - "default.d"
    - "conf.d"
    - "http.d"
    - "vhost.d"
    - "stream.d"

- name: Setup nginx configurations
  ansible.builtin.template:
    src: "{{ item }}.conf.j2"
    dest: "{{ nginx_service_config_path }}/{{ item }}.conf"
    mode: '0644'
    owner: root
    group: root
  loop:
    - nginx
    - http
    - stream
    - static
  loop_control:
    label: "{{ item }}"

- name: Create default http server configurations
  ansible.builtin.template:
    src: config/default.conf.j2
    dest: "{{ nginx_service_config_path }}/conf.d/default.conf"
  when:
    - nginx_default_server is defined and nginx_default_server is iterable and nginx_default_server | selectattr('enabled', 'defined') | selectattr('enabled', 'equalto', true) | list | length > 0
  notify: 
    - reload nginx

- name: Create vhost configurations
  ansible.builtin.template:
    src: config/vhost.conf.j2
    dest: "{{ nginx_service_config_path }}/vhost.d/vhost_{{ item.name }}.conf"
  loop: "{{ nginx_vhost_servers | selectattr('enabled', 'equalto', true) }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - nginx_vhost_servers is defined and nginx_vhost_servers is iterable and nginx_vhost_servers | selectattr('enabled', 'defined') | selectattr('enabled', 'equalto', true) | list | length > 0
  notify: 
    - reload nginx

- name: Create static file server configurations
  ansible.builtin.template:
    src: config/static.conf.j2
    dest: "{{ nginx_service_config_path }}/static.d/static_{{ item.name }}.conf"
  loop: "{{ nginx_static_file_servers | selectattr('enabled', 'equalto', true) }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - nginx_static_file_servers is defined and nginx_static_file_servers is iterable and nginx_static_file_servers | selectattr('enabled', 'defined') | selectattr('enabled', 'equalto', true) | list | length > 0
  notify: 
    - reload nginx

- name: Create http load balancer configurations
  ansible.builtin.template:
    src: config/http.conf.j2
    dest: "{{ nginx_service_config_path }}/http.d/http_{{ item.name }}.conf"
  loop: "{{ nginx_http_loadbalancers | selectattr('enabled', 'equalto', true) }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - nginx_http_loadbalancers is defined and nginx_http_loadbalancers is iterable and nginx_http_loadbalancers | selectattr('enabled', 'defined') | selectattr('enabled', 'equalto', true) | list | length > 0
  notify: 
    - reload nginx

- name: Create tcp load balancer configurations
  ansible.builtin.template:
    src: config/stream.conf.j2
    dest: "{{ nginx_service_config_path }}/stream.d/stream_{{ item.name }}.conf"
  loop: "{{ nginx_stream_loadbalancers | selectattr('enabled', 'equalto', true) }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - nginx_stream_loadbalancers is defined and nginx_stream_loadbalancers is iterable and nginx_stream_loadbalancers | selectattr('enabled', 'defined') | selectattr('enabled', 'equalto', true) | list | length > 0
  notify: 
    - reload nginx

- name: Ensure Nginx service is started and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
  notify: 
    - reload nginx
