---

- name: Create HTTP configuration directories
  ansible.builtin.include_tasks: create-dirs-config.yml
  vars:
    directory_type: "static configuration directory"
  loop:
    - "http.d"

- name: Create HTTP configuration directories
  ansible.builtin.include_tasks: create-dirs-root.yml
  vars:
    directory_type: "static file directory"
  loop:
    - "http"

- name: Create HTTP SSL directories
  ansible.builtin.include_tasks: create-dirs-ssl.yml
  vars:
    directory_type: "ssl directory"
  loop:
    - "http"

- name: Create http load balancer configurations
  ansible.builtin.template:
    src: config/http.conf.j2
    dest: "{{ nginx_service_config_path }}/http.d/http_{{ item.name }}.conf"
    mode: '0644'
    owner: root
    group: root
  loop: "{{ nginx_http_loadbalancers | selectattr('enabled', 'equalto', true) }}"
  loop_control:
    label: "{{ item.name }}"
