---

- name: Create sysctl configuration file for Nginx
  ansible.builtin.template:
    src: config/sysctl.conf.j2
    dest: "/etc/sysctl.d/{{ nginx_sysctl_conf_file }}"
    owner: root
    group: root
    mode: '0644'
  register: sysctl_config

- name: Apply sysctl parameters
  ansible.posix.sysctl:
    sysctl_file: "/etc/sysctl.d/{{ nginx_sysctl_conf_file }}"
    reload: true
  when: sysctl_config.changed
